-- JECO MainProca - Dummy Products Data
-- Import this file through phpMyAdmin to add 100 sample products
-- Table: wp_jeco_mainproca_products
-- 
-- Note: This assumes your WordPress table prefix is 'wp_'. 
-- If your prefix is different, replace 'wp_' with your actual prefix.

INSERT INTO `wp_jeco_mainproca_products` (`name`, `quantity`, `price`, `description`, `created_at`, `updated_at`) VALUES
('Premium Wireless Headphones', 25.50, 149.99, 'High-quality wireless headphones with noise cancellation and 30-hour battery life. Perfect for music lovers and professionals.', NOW(), NOW()),
('Organic Cotton T-Shirt', 150.00, 29.99, 'Comfortable and sustainable organic cotton t-shirt available in multiple colors. Eco-friendly and ethically made.', NOW(), NOW()),
('Stainless Steel Water Bottle', 75.25, 24.99, 'Insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours. BPA-free and leak-proof.', NOW(), NOW()),
('Bluetooth Portable Speaker', 42.00, 79.99, 'Compact wireless speaker with powerful sound and 20-hour battery. Waterproof design perfect for outdoor adventures.', NOW(), NOW()),
('Ergonomic Office Chair', 8.00, 299.99, 'Professional ergonomic office chair with lumbar support and adjustable height. Designed for all-day comfort and productivity.', NOW(), NOW()),
('Smart Fitness Tracker', 65.75, 199.99, 'Advanced fitness tracker with heart rate monitoring, GPS, and sleep tracking. Compatible with iOS and Android.', NOW(), NOW()),
('Ceramic Coffee Mug Set', 120.00, 39.99, 'Set of 4 handcrafted ceramic coffee mugs with unique glazed finish. Microwave and dishwasher safe.', NOW(), NOW()),
('LED Desk Lamp', 35.50, 59.99, 'Adjustable LED desk lamp with touch controls and USB charging port. Energy-efficient with multiple brightness levels.', NOW(), NOW()),
('Bamboo Cutting Board', 90.25, 34.99, 'Large bamboo cutting board with juice groove and non-slip feet. Antimicrobial and eco-friendly kitchen essential.', NOW(), NOW()),
('Wireless Phone Charger', 55.00, 49.99, 'Fast wireless charging pad compatible with all Qi-enabled devices. Sleek design with LED indicator lights.', NOW(), NOW()),
('Memory Foam Pillow', 48.75, 69.99, 'Contoured memory foam pillow with cooling gel layer. Provides optimal neck and spine alignment for better sleep.', NOW(), NOW()),
('Stainless Steel Cookware Set', 12.00, 249.99, 'Professional 10-piece stainless steel cookware set with tri-ply construction. Oven and dishwasher safe.', NOW(), NOW()),
('Yoga Mat Premium', 85.50, 89.99, 'Extra-thick yoga mat with superior grip and cushioning. Made from eco-friendly TPE material with alignment lines.', NOW(), NOW()),
('Digital Kitchen Scale', 72.25, 44.99, 'Precision digital kitchen scale with tare function and multiple units. Tempered glass platform with LCD display.', NOW(), NOW()),
('Leather Laptop Bag', 28.00, 129.99, 'Genuine leather laptop bag with padded compartment for 15-inch laptops. Multiple pockets for organization.', NOW(), NOW()),
('Essential Oil Diffuser', 95.75, 79.99, 'Ultrasonic essential oil diffuser with color-changing LED lights. Whisper-quiet operation with timer settings.', NOW(), NOW()),
('Microfiber Towel Set', 200.00, 49.99, 'Set of 6 ultra-soft microfiber towels in assorted sizes. Quick-dry and highly absorbent for bath and beach.', NOW(), NOW()),
('Portable Phone Stand', 150.25, 19.99, 'Adjustable aluminum phone stand compatible with all smartphone sizes. Foldable design perfect for desk or travel.', NOW(), NOW()),
('Insulated Lunch Box', 68.50, 34.99, 'Insulated lunch box with multiple compartments and ice pack. Keeps food fresh and organized for work or school.', NOW(), NOW()),
('Bluetooth Keyboard', 32.00, 99.99, 'Slim wireless keyboard with backlit keys and long battery life. Compatible with tablets, phones, and computers.', NOW(), NOW()),
('Ceramic Plant Pot Set', 110.75, 59.99, 'Set of 3 decorative ceramic plant pots with drainage holes and saucers. Perfect for indoor herbs and succulents.', NOW(), NOW()),
('USB-C Hub Adapter', 45.25, 69.99, 'Multi-port USB-C hub with HDMI, USB 3.0, and SD card slots. Compact design for laptops and tablets.', NOW(), NOW()),
('Silicone Baking Mat Set', 180.00, 24.99, 'Set of 2 non-stick silicone baking mats. Reusable alternative to parchment paper, oven safe up to 480°F.', NOW(), NOW()),
('Wireless Mouse', 88.50, 39.99, 'Ergonomic wireless mouse with precision tracking and long battery life. Comfortable grip for extended use.', NOW(), NOW()),
('Glass Food Storage Set', 52.75, 79.99, 'Set of 10 glass food storage containers with airtight lids. Microwave, oven, and freezer safe.', NOW(), NOW()),
('Adjustable Dumbbell Set', 15.00, 199.99, 'Space-saving adjustable dumbbells with weight range from 5-50 lbs each. Quick weight change mechanism.', NOW(), NOW()),
('Aromatherapy Candle Set', 125.25, 44.99, 'Set of 4 soy wax candles with natural essential oils. Long-lasting burn time with relaxing scents.', NOW(), NOW()),
('Portable Blender', 38.00, 89.99, 'Rechargeable portable blender perfect for smoothies on-the-go. USB charging with powerful motor and leak-proof design.', NOW(), NOW()),
('Wooden Spice Rack', 95.50, 69.99, 'Bamboo spice rack with 20 glass jars and labels. Rotating design saves counter space and keeps spices organized.', NOW(), NOW()),
('Bluetooth Earbuds', 62.25, 129.99, 'True wireless earbuds with active noise cancellation and wireless charging case. Premium sound quality and comfort.', NOW(), NOW()),
('Throw Pillow Covers', 140.00, 29.99, 'Set of 4 decorative throw pillow covers in modern patterns. Machine washable with hidden zipper closure.', NOW(), NOW()),
('Digital Photo Frame', 22.75, 159.99, 'Smart digital photo frame with WiFi connectivity and mobile app. Display photos and videos from anywhere.', NOW(), NOW()),
('Stainless Steel Thermos', 78.50, 54.99, 'Double-wall vacuum insulated thermos keeps beverages hot or cold for hours. Leak-proof with wide mouth opening.', NOW(), NOW()),
('Resistance Band Set', 105.00, 34.99, 'Complete resistance band workout set with door anchor and exercise guide. Multiple resistance levels included.', NOW(), NOW()),
('Bamboo Desk Organizer', 58.25, 49.99, 'Multi-compartment bamboo desk organizer for pens, papers, and office supplies. Sustainable and stylish design.', NOW(), NOW()),
('Wireless Charging Stand', 85.75, 59.99, 'Adjustable wireless charging stand with fast charging capability. Works with phones in portrait or landscape mode.', NOW(), NOW()),
('Ceramic Dinner Plate Set', 92.00, 89.99, 'Set of 8 elegant ceramic dinner plates with modern design. Chip-resistant and dishwasher safe.', NOW(), NOW()),
('Laptop Cooling Pad', 35.50, 44.99, 'Laptop cooling pad with dual fans and adjustable height. Reduces laptop temperature and improves performance.', NOW(), NOW()),
('Silicone Ice Cube Trays', 165.25, 19.99, 'Set of 2 flexible silicone ice cube trays with easy-release design. Makes 14 large ice cubes per tray.', NOW(), NOW()),
('Wireless Security Camera', 18.00, 179.99, 'HD wireless security camera with night vision and motion detection. Mobile app control with cloud storage option.', NOW(), NOW()),
('Bamboo Salad Bowl Set', 115.75, 64.99, 'Set of 3 bamboo salad bowls in different sizes with serving utensils. Natural finish and food-safe coating.', NOW(), NOW()),
('USB Desk Fan', 72.50, 29.99, 'Quiet USB-powered desk fan with adjustable speed and tilt. Perfect for personal cooling in office or home.', NOW(), NOW()),
('Leather Wallet', 48.25, 79.99, 'Genuine leather bifold wallet with RFID blocking technology. Multiple card slots and bill compartment.', NOW(), NOW()),
('Glass Water Pitcher', 125.00, 39.99, 'Elegant glass water pitcher with stainless steel lid and infuser. Perfect for fruit-infused water and beverages.', NOW(), NOW()),
('Wireless Doorbell', 28.75, 69.99, 'Smart wireless doorbell with HD video and two-way audio. Motion detection with smartphone notifications.', NOW(), NOW()),
('Ceramic Mixing Bowl Set', 155.50, 54.99, 'Set of 5 ceramic mixing bowls in graduated sizes with non-slip bases. Microwave and dishwasher safe.', NOW(), NOW()),
('Portable Power Bank', 65.00, 49.99, 'High-capacity portable power bank with fast charging and multiple USB ports. LED display shows remaining power.', NOW(), NOW()),
('Wooden Cutting Board Set', 82.25, 74.99, 'Set of 3 acacia wood cutting boards in different sizes. Reversible with juice groove and hanging holes.', NOW(), NOW()),
('Smart Light Bulbs', 195.75, 89.99, 'Set of 4 smart LED bulbs with color changing and dimming features. Voice control compatible with Alexa and Google.', NOW(), NOW()),
('Stainless Steel Mixing Bowls', 108.00, 44.99, 'Set of 6 stainless steel mixing bowls with measurement marks and pour spouts. Stackable design saves space.', NOW(), NOW()),
('Wireless Car Charger', 42.50, 54.99, 'Automatic wireless car charger with phone holder and fast charging. Compatible with most smartphones.', NOW(), NOW()),
('Bamboo Utensil Set', 175.25, 24.99, 'Portable bamboo utensil set with fork, knife, spoon, and chopsticks. Includes carrying case for travel.', NOW(), NOW()),
('Digital Alarm Clock', 58.75, 39.99, 'Modern digital alarm clock with wireless charging pad and USB ports. Adjustable brightness and snooze function.', NOW(), NOW()),
('Silicone Oven Mitts', 135.00, 29.99, 'Heat-resistant silicone oven mitts with textured grip. Waterproof and easy to clean, protects up to 450°F.', NOW(), NOW()),
('Bluetooth Shower Speaker', 25.50, 49.99, 'Waterproof Bluetooth speaker designed for shower use. Suction cup mount with hands-free calling capability.', NOW(), NOW()),
('Glass Spice Jar Set', 98.25, 59.99, 'Set of 12 glass spice jars with airtight lids and labels. Uniform size fits most spice racks and drawers.', NOW(), NOW()),
('Wireless Keyboard and Mouse', 52.00, 79.99, 'Wireless keyboard and mouse combo with long battery life. Ergonomic design with quiet keys and precise tracking.', NOW(), NOW()),
('Ceramic Coffee Grinder', 75.75, 129.99, 'Manual ceramic burr coffee grinder with adjustable grind settings. Consistent grind for perfect coffee extraction.', NOW(), NOW()),
('Portable Laptop Stand', 118.50, 69.99, 'Adjustable aluminum laptop stand with heat dissipation design. Ergonomic height and angle for comfortable typing.', NOW(), NOW()),
('Silicone Food Covers', 185.25, 19.99, 'Set of 6 stretchable silicone food covers in various sizes. Reusable alternative to plastic wrap and foil.', NOW(), NOW()),
('Smart Thermostat', 12.00, 199.99, 'Programmable smart thermostat with WiFi connectivity and energy-saving features. Mobile app control and scheduling.', NOW(), NOW()),
('Bamboo Phone Holder', 88.75, 34.99, 'Adjustable bamboo phone holder for desk or bedside table. Eco-friendly design accommodates various phone sizes.', NOW(), NOW()),
('Wireless Headphone Stand', 45.50, 44.99, 'Elegant headphone stand with wireless charging base. Aluminum construction with non-slip base and cable management.', NOW(), NOW()),
('Glass Measuring Cup Set', 162.00, 39.99, 'Set of 4 glass measuring cups with easy-pour spouts and measurement markings. Microwave and dishwasher safe.', NOW(), NOW()),
('Portable Bluetooth Printer', 28.25, 149.99, 'Compact wireless printer for photos and documents. Battery-powered with mobile app for easy printing anywhere.', NOW(), NOW()),
('Ceramic Herb Planter', 95.75, 49.99, 'Indoor ceramic herb planter with drainage system and water level indicator. Perfect for growing fresh herbs.', NOW(), NOW()),
('USB-C Cable Set', 155.50, 24.99, 'Set of 3 USB-C cables in different lengths with fast charging and data transfer. Durable braided design.', NOW(), NOW()),
('Wireless Gaming Mouse', 38.00, 89.99, 'High-precision wireless gaming mouse with customizable RGB lighting. Programmable buttons and long battery life.', NOW(), NOW()),
('Silicone Pot Holders', 125.25, 19.99, 'Set of 4 heat-resistant silicone pot holders with hanging loops. Non-slip surface protects countertops and hands.', NOW(), NOW()),
('Smart Smoke Detector', 22.75, 119.99, 'WiFi-enabled smoke detector with smartphone alerts and voice announcements. Battery backup and easy installation.', NOW(), NOW()),
('Bamboo Laptop Tray', 78.50, 59.99, 'Adjustable bamboo laptop tray with cooling vents and mouse pad. Perfect for bed or couch use with ergonomic design.', NOW(), NOW()),
('Wireless Earphone Case', 195.00, 29.99, 'Protective case for wireless earphones with carabiner clip. Shockproof and waterproof with precise cutouts.', NOW(), NOW()),
('Glass Food Prep Containers', 65.25, 69.99, 'Set of 8 glass meal prep containers with snap-lock lids. Portion control design perfect for healthy meal planning.', NOW(), NOW()),
('Portable Phone Sanitizer', 52.75, 79.99, 'UV-C phone sanitizer that kills 99.9% of germs and bacteria. Fits most smartphones with aromatherapy function.', NOW(), NOW()),
('Ceramic Soap Dispenser', 135.50, 34.99, 'Elegant ceramic soap dispenser with pump mechanism. Modern design complements any bathroom or kitchen decor.', NOW(), NOW()),
('Wireless Backup Camera', 18.00, 159.99, 'Wireless backup camera system with LCD monitor. Easy installation with night vision and parking guidelines.', NOW(), NOW()),
('Bamboo Cheese Board Set', 108.25, 89.99, 'Bamboo cheese board with hidden drawer containing cheese knives and markers. Perfect for entertaining guests.', NOW(), NOW()),
('Smart Door Lock', 8.75, 249.99, 'Keyless smart door lock with fingerprint and code access. Smartphone app control with activity monitoring.', NOW(), NOW()),
('Silicone Baking Cups', 175.50, 24.99, 'Set of 12 reusable silicone baking cups in assorted colors. Non-stick surface perfect for muffins and cupcakes.', NOW(), NOW()),
('Wireless Weather Station', 35.00, 129.99, 'Digital weather station with outdoor sensor and smartphone app. Displays temperature, humidity, and forecasts.', NOW(), NOW()),
('Glass Tea Infuser Bottle', 92.25, 44.99, 'Borosilicate glass bottle with built-in tea infuser and protective sleeve. Perfect for hot or cold tea brewing.', NOW(), NOW()),
('Portable Air Purifier', 58.75, 179.99, 'Compact air purifier with HEPA filter and UV-C light. Removes allergens, dust, and odors from small spaces.', NOW(), NOW()),
('Bamboo Drawer Organizer', 145.00, 39.99, 'Expandable bamboo drawer organizer with adjustable dividers. Perfect for kitchen utensils and office supplies.', NOW(), NOW()),
('Wireless Charging Mouse Pad', 25.50, 49.99, 'Large mouse pad with built-in wireless charging zone. Smooth surface for precise mouse tracking and phone charging.', NOW(), NOW()),
('Ceramic Candle Holders', 118.75, 54.99, 'Set of 3 ceramic candle holders in modern geometric designs. Fits standard pillar and taper candles safely.', NOW(), NOW()),
('Smart Garden System', 12.25, 199.99, 'Hydroponic smart garden with LED grow lights and automated watering. Grow herbs and vegetables indoors year-round.', NOW(), NOW()),
('Silicone Stretch Lids', 185.50, 29.99, 'Set of 6 stretchable silicone lids that fit various container sizes. Airtight seal keeps food fresh longer.', NOW(), NOW()),
('Wireless Video Doorbell', 42.00, 189.99, 'Smart video doorbell with HD camera and two-way audio. Motion detection with cloud storage and mobile alerts.', NOW(), NOW()),
('Bamboo Toilet Paper Holder', 95.25, 44.99, 'Wall-mounted bamboo toilet paper holder with phone shelf. Eco-friendly design with easy installation hardware.', NOW(), NOW()),
('Portable Espresso Maker', 68.75, 149.99, 'Manual portable espresso maker for travel and camping. No electricity required, makes authentic espresso anywhere.', NOW(), NOW()),
('Glass Salad Dressing Bottles', 155.00, 34.99, 'Set of 4 glass bottles with pour spouts for homemade dressings. Airtight caps keep dressings fresh and flavorful.', NOW(), NOW()),
('Wireless Meat Thermometer', 28.50, 89.99, 'Bluetooth meat thermometer with smartphone app and preset temperatures. Monitor cooking progress from anywhere.', NOW(), NOW()),
('Ceramic Utensil Crock', 125.75, 39.99, 'Large ceramic utensil holder with drainage holes and removable divider. Keeps countertop organized and utensils dry.', NOW(), NOW()),
('Smart Light Switch', 52.00, 79.99, 'WiFi smart light switch with dimming capability and scheduling. Voice control compatible with smart home systems.', NOW(), NOW()),
('Bamboo Bread Box', 85.50, 69.99, 'Large bamboo bread box with roll-top lid and cutting board surface. Keeps bread fresh while saving counter space.', NOW(), NOW()),
('Wireless Charging Alarm Clock', 75.25, 99.99, 'Digital alarm clock with wireless charging pad and ambient lighting. Multiple alarms with gradual wake-up feature.', NOW(), NOW()),
('Silicone Cooking Utensil Set', 165.75, 49.99, 'Set of 8 heat-resistant silicone cooking utensils with wooden handles. Non-stick safe and dishwasher friendly.', NOW(), NOW()),
('Smart Plug Set', 38.00, 59.99, 'Set of 4 WiFi smart plugs with energy monitoring and scheduling. Control appliances remotely via smartphone app.', NOW(), NOW()),
('Glass Olive Oil Dispenser', 112.25, 44.99, 'Premium glass olive oil dispenser with pour spout and drip-free design. Keeps oil fresh with airtight seal.', NOW(), NOW()),
('Wireless Backup Drive', 22.75, 179.99, 'Portable wireless backup drive with automatic syncing and mobile app. Secure cloud storage for photos and documents.', NOW(), NOW()),
('Bamboo Serving Tray Set', 148.50, 79.99, 'Set of 3 bamboo serving trays in different sizes with handles. Perfect for breakfast in bed or entertaining guests.', NOW(), NOW()),
('Smart Water Bottle', 65.00, 129.99, 'Insulated smart water bottle with hydration tracking and temperature display. Smartphone app reminds you to drink water.', NOW(), NOW()),
('Ceramic Mixing Spoon Set', 195.25, 29.99, 'Set of 4 ceramic mixing spoons in different sizes with comfortable handles. Heat-resistant and stain-resistant design.', NOW(), NOW()),
('Wireless Car Phone Mount', 45.75, 54.99, 'Magnetic wireless car mount with fast charging capability. Secure hold with 360-degree rotation and easy installation.', NOW(), NOW()),
('Glass Storage Jar Set', 88.00, 64.99, 'Set of 6 airtight glass storage jars with bamboo lids. Perfect for pantry organization and keeping food fresh.', NOW(), NOW()),
('Smart Doorbell Chime', 32.50, 89.99, 'Wireless doorbell chime with customizable tones and volume control. Multiple receivers for whole-house coverage.', NOW(), NOW()),
('Silicone Trivet Set', 175.00, 24.99, 'Set of 4 flexible silicone trivets with honeycomb design. Heat-resistant up to 450°F and dishwasher safe.', NOW(), NOW()),
('Portable Projector', 15.25, 299.99, 'Mini portable projector with WiFi connectivity and built-in speakers. Perfect for outdoor movies and presentations.', NOW(), NOW());